//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessTrip
    {
        public int TripId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public int Budget { get; set; }
        public string Destination { get; set; }
        public string Purpose { get; set; }
        public System.DateTime PeriodStart { get; set; }
        public System.DateTime PeriodEnd { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
