//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmploymentContract
    {
        public int ContractId { get; set; }
        public System.DateTime DateOfCompilation { get; set; }
        public System.DateTime DateOfAcceptance { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public int Salary { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
